/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AddItemController;
import Controller.CreateBrandController;
import Controller.UpdateController;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Adithya
 */
public class CreateBrand extends javax.swing.JFrame {
    
    /**
     * Creates new form CreateBrand
     */
    public CreateBrand() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ResultSet rs = new UpdateController().updateBrandsCmb();
        try {  
            brandNameRmvCmb.removeAllItems();
            brandNameAddItmCmb.removeAllItems();
            brandNameRmvItmCmb.removeAllItems();
            while(rs.next()){
                
                brandNameRmvCmb.addItem(rs.getString("table_name"));
                brandNameAddItmCmb.addItem(rs.getString("table_name"));
                brandNameRmvItmCmb.addItem(rs.getString("table_name"));
            }
            brandNameRmvCmb.setSelectedItem(null);
            brandNameAddItmCmb.setSelectedItem(null);
            brandNameRmvItmCmb.setSelectedItem(null);
        } catch (SQLException ex) {
            Logger.getLogger(CreateBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    String getCategoryRBtns()
{
    if(mensRBtn.isSelected())
    {
        return "mens";
    }
    else if(ladiesRBtn.isSelected())
    {
        return "ladies";
    }
    else if(kidsRBtn.isSelected())
    {
        return "kids";
    }
    else
    {
        return null;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        createTb = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        brandNameAddTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        removeBtn1 = new javax.swing.JButton();
        brandNameRmvCmb = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        brandNameAddItmCmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        itemNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ladiesRBtn = new javax.swing.JRadioButton();
        mensRBtn = new javax.swing.JRadioButton();
        kidsRBtn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        itemAddBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        noOfItemsTF = new javax.swing.JSpinner();
        pane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        brandNameRmvItmCmb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        itemNamesCmb = new javax.swing.JComboBox<>();
        itemInstanceRemoveBtn = new javax.swing.JButton();
        showItemsBtn = new javax.swing.JButton();
        noOfItemsLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        noOfItemLbl = new javax.swing.JLabel();
        itemInstanceRemoveBtn1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        noOfItemsRmvTF = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        createTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createTbMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(211, 211, 211));

        addBtn.setBackground(new java.awt.Color(229, 228, 226));
        addBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        addBtn.setText("Add");
        addBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addBtn.setFocusPainted(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        brandNameAddTF.setBackground(new java.awt.Color(229, 228, 226));
        brandNameAddTF.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        brandNameAddTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));

        jLabel1.setText("Brand Name");

        jPanel5.setBackground(new java.awt.Color(96, 130, 182));

        jLabel12.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(211, 211, 211));
        jLabel12.setText("ADD BRAND");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandNameAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(brandNameAddTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        createTb.addTab("Add Brand ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(211, 211, 211));

        jLabel2.setText("Brand Name");

        removeBtn1.setBackground(new java.awt.Color(229, 228, 226));
        removeBtn1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        removeBtn1.setText("Remove");
        removeBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removeBtn1.setFocusPainted(false);
        removeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtn1ActionPerformed(evt);
            }
        });

        brandNameRmvCmb.setBackground(new java.awt.Color(229, 228, 226));
        brandNameRmvCmb.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        brandNameRmvCmb.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));

        jPanel6.setBackground(new java.awt.Color(96, 130, 182));

        jLabel13.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(211, 211, 211));
        jLabel13.setText("REMOVE BRAND");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandNameRmvCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brandNameRmvCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(removeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        createTb.addTab("Remove Brand", jPanel3);

        jPanel4.setBackground(new java.awt.Color(211, 211, 211));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });

        brandNameAddItmCmb.setBackground(new java.awt.Color(229, 228, 226));
        brandNameAddItmCmb.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        brandNameAddItmCmb.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));

        jLabel3.setText("Brand Name");

        itemNameTF.setBackground(new java.awt.Color(229, 228, 226));
        itemNameTF.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemNameTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));

        jLabel4.setText("Item Name");

        buttonGroup1.add(ladiesRBtn);
        ladiesRBtn.setText("Ladie's");

        buttonGroup1.add(mensRBtn);
        mensRBtn.setText("Men's");

        buttonGroup1.add(kidsRBtn);
        kidsRBtn.setText("Kids's");

        jLabel5.setText("Category");

        jLabel6.setText("Number of Items");

        itemAddBtn.setBackground(new java.awt.Color(229, 228, 226));
        itemAddBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemAddBtn.setText("Add");
        itemAddBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemAddBtn.setFocusPainted(false);
        itemAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Price");

        priceTF.setBackground(new java.awt.Color(229, 228, 226));
        priceTF.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        priceTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));

        jPanel7.setBackground(new java.awt.Color(96, 130, 182));

        jLabel14.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(211, 211, 211));
        jLabel14.setText("ADD ITEM");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        noOfItemsTF.setFont(new java.awt.Font("Segoe UI Variable", 0, 13)); // NOI18N
        noOfItemsTF.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemNameTF)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandNameAddItmCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(mensRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ladiesRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kidsRBtn))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noOfItemsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mensRBtn)
                            .addComponent(ladiesRBtn)
                            .addComponent(kidsRBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(noOfItemsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(brandNameAddItmCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(itemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(itemAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        createTb.addTab("Add Items", jPanel4);

        pane.setBackground(new java.awt.Color(211, 211, 211));
        pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneMouseEntered(evt);
            }
        });

        jLabel7.setText("Number of Items");

        jLabel8.setText("Item Names");

        brandNameRmvItmCmb.setBackground(new java.awt.Color(229, 228, 226));
        brandNameRmvItmCmb.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        brandNameRmvItmCmb.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        brandNameRmvItmCmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brandNameRmvItmCmbMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brandNameRmvItmCmbMouseExited(evt);
            }
        });
        brandNameRmvItmCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameRmvItmCmbActionPerformed(evt);
            }
        });

        jLabel9.setText("Brand Name");

        itemNamesCmb.setBackground(new java.awt.Color(229, 228, 226));
        itemNamesCmb.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemNamesCmb.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        itemNamesCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemNamesCmbItemStateChanged(evt);
            }
        });
        itemNamesCmb.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                itemNamesCmbPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        itemNamesCmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemNamesCmbMouseExited(evt);
            }
        });
        itemNamesCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNamesCmbActionPerformed(evt);
            }
        });

        itemInstanceRemoveBtn.setBackground(new java.awt.Color(229, 228, 226));
        itemInstanceRemoveBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemInstanceRemoveBtn.setText("Remove");
        itemInstanceRemoveBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemInstanceRemoveBtn.setFocusPainted(false);
        itemInstanceRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstanceRemoveBtnActionPerformed(evt);
            }
        });

        showItemsBtn.setText("Show Items");
        showItemsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showItemsBtnMouseClicked(evt);
            }
        });
        showItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showItemsBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Available Items:");

        jButton1.setBackground(new java.awt.Color(229, 228, 226));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton1.setText("Remove Item");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        noOfItemLbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        noOfItemLbl.setText("--");

        itemInstanceRemoveBtn1.setBackground(new java.awt.Color(229, 228, 226));
        itemInstanceRemoveBtn1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemInstanceRemoveBtn1.setText("Add");
        itemInstanceRemoveBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemInstanceRemoveBtn1.setFocusPainted(false);
        itemInstanceRemoveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstanceRemoveBtn1ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(96, 130, 182));

        jLabel15.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(211, 211, 211));
        jLabel15.setText("EDIT ITEM");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        noOfItemsRmvTF.setFont(new java.awt.Font("Segoe UI Variable", 0, 13)); // NOI18N
        noOfItemsRmvTF.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showItemsBtn)
                                    .addGroup(paneLayout.createSequentialGroup()
                                        .addComponent(brandNameRmvItmCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(noOfItemsRmvTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemNamesCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noOfItemLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(103, 103, 103)
                        .addComponent(noOfItemsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addComponent(itemInstanceRemoveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemInstanceRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(noOfItemsLbl))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(brandNameRmvItmCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(noOfItemsRmvTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showItemsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(itemNamesCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(noOfItemLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(itemInstanceRemoveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(itemInstanceRemoveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        createTb.addTab("Edit Items", pane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(createTb, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createTb)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        ResultSet rs = new UpdateController().updateBrandsCmb();
        CreateBrandController.create(brandNameAddTF.getText(),rs);
         rs = new UpdateController().updateBrandsCmb();
        brandNameRmvCmb.removeAllItems();
        brandNameAddItmCmb.removeAllItems();
        brandNameRmvItmCmb.removeAllItems();
        try {   
            
            while(rs.next()){
                
                brandNameRmvCmb.addItem(rs.getString("table_name"));
                brandNameAddItmCmb.addItem(rs.getString("table_name"));
                brandNameRmvItmCmb.addItem(rs.getString("table_name"));
            }
        brandNameRmvCmb.setSelectedItem(null);
        brandNameAddItmCmb.setSelectedItem(null);
        brandNameRmvItmCmb.setSelectedItem(null);
        brandNameAddTF.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(CreateBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void removeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtn1ActionPerformed
        CreateBrandController.remove(brandNameRmvCmb.getSelectedItem().toString());
        
        ResultSet rs = new UpdateController().updateBrandsCmb();
        brandNameRmvCmb.removeAllItems();
        brandNameAddItmCmb.removeAllItems();
        brandNameRmvItmCmb.removeAllItems();
        try {   
            
            while(rs.next()){
                
                brandNameRmvCmb.addItem(rs.getString("table_name"));
                brandNameAddItmCmb.addItem(rs.getString("table_name"));
                brandNameRmvItmCmb.addItem(rs.getString("table_name"));
            }
            brandNameRmvCmb.setSelectedItem(null);
            brandNameAddItmCmb.setSelectedItem(null);
            brandNameRmvItmCmb.setSelectedItem(null);
        } catch (SQLException ex) {
            
        }
        
    }//GEN-LAST:event_removeBtn1ActionPerformed

    private void createTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createTbMouseClicked
       
    }//GEN-LAST:event_createTbMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
       
    }//GEN-LAST:event_jPanel4MouseClicked

    private void brandNameRmvItmCmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandNameRmvItmCmbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameRmvItmCmbMouseClicked

    private void itemAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddBtnActionPerformed
       
        new AddItemController().insert(brandNameAddItmCmb.getSelectedItem().toString(), itemNameTF.getText(), getCategoryRBtns(),priceTF.getText(), noOfItemsTF.getValue().toString());
        
        itemNameTF.setText("");
        priceTF.setText(""); 
        noOfItemsTF.setValue(0);
        brandNameAddItmCmb.setSelectedItem(null);
     
    }//GEN-LAST:event_itemAddBtnActionPerformed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void brandNameRmvItmCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameRmvItmCmbActionPerformed
         
        
    }//GEN-LAST:event_brandNameRmvItmCmbActionPerformed

    private void brandNameRmvItmCmbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandNameRmvItmCmbMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameRmvItmCmbMouseExited

    private void paneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneMouseEntered
   
    }//GEN-LAST:event_paneMouseEntered

    private void showItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showItemsBtnActionPerformed
        
    }//GEN-LAST:event_showItemsBtnActionPerformed

    private void showItemsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showItemsBtnMouseClicked
        try {
            ResultSet rs = new UpdateController().updateItemCmb(brandNameRmvItmCmb.getSelectedItem().toString());
            itemNamesCmb.removeAllItems();
            
            
            
            while(rs.next()){
            
                itemNamesCmb.addItem(rs.getString("item_name"));
                
            
                
            }
                
                } catch (SQLException ex) {
            Logger.getLogger(CreateBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_showItemsBtnMouseClicked

    private void itemInstanceRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstanceRemoveBtnActionPerformed
        
        AddItemController.setNoOfItemsRmv(brandNameRmvItmCmb.getSelectedItem().toString(), itemNamesCmb.getSelectedItem().toString(), noOfItemsRmvTF.getValue().toString());
        noOfItemLbl.setText(AddItemController.getNoOfItems(brandNameRmvItmCmb.getSelectedItem().toString(), itemNamesCmb.getSelectedItem().toString()));
       
        noOfItemsRmvTF.setValue(null);
    }//GEN-LAST:event_itemInstanceRemoveBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AddItemController().removeItem(brandNameRmvItmCmb.getSelectedItem().toString(),itemNamesCmb.getSelectedItem().toString());
        itemNamesCmb.removeItem(itemNamesCmb.getSelectedItem());
        
        /*try {
            ResultSet rs = new UpdateController().updateItemCmb(brandNameRmvItmCmb.getSelectedItem().toString());
            itemNamesCmb.removeAllItems();
            
            
            
            while(rs.next()){
            
                itemNamesCmb.addItem(rs.getString("item_name"));
            
                
            }
                
                } catch (SQLException ex) {
            Logger.getLogger(CreateBrand.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemNamesCmbPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_itemNamesCmbPopupMenuWillBecomeInvisible
        
    }//GEN-LAST:event_itemNamesCmbPopupMenuWillBecomeInvisible

    private void itemNamesCmbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemNamesCmbMouseExited
        
    }//GEN-LAST:event_itemNamesCmbMouseExited

    private void itemNamesCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNamesCmbActionPerformed
        
    }//GEN-LAST:event_itemNamesCmbActionPerformed

    private void itemNamesCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemNamesCmbItemStateChanged
         noOfItemLbl.setText(AddItemController.getNoOfItems(brandNameRmvItmCmb.getSelectedItem().toString(), itemNamesCmb.getSelectedItem().toString()));  
         
    }//GEN-LAST:event_itemNamesCmbItemStateChanged

    private void itemInstanceRemoveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstanceRemoveBtn1ActionPerformed
        new AddItemController().setNoOfItemsAdd(brandNameRmvItmCmb.getSelectedItem().toString(), itemNamesCmb.getSelectedItem().toString(), noOfItemsRmvTF.getValue().toString());
        noOfItemLbl.setText(AddItemController.getNoOfItems(brandNameRmvItmCmb.getSelectedItem().toString(), itemNamesCmb.getSelectedItem().toString()));
        //itemNamesCmb.setSelectedItem(null);
        noOfItemsRmvTF.setValue(null);
    }//GEN-LAST:event_itemInstanceRemoveBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBrand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> brandNameAddItmCmb;
    private javax.swing.JTextField brandNameAddTF;
    private javax.swing.JComboBox<String> brandNameRmvCmb;
    private javax.swing.JComboBox<String> brandNameRmvItmCmb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane createTb;
    private javax.swing.JButton itemAddBtn;
    private javax.swing.JButton itemInstanceRemoveBtn;
    private javax.swing.JButton itemInstanceRemoveBtn1;
    private javax.swing.JTextField itemNameTF;
    private javax.swing.JComboBox<String> itemNamesCmb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton kidsRBtn;
    private javax.swing.JRadioButton ladiesRBtn;
    private javax.swing.JRadioButton mensRBtn;
    private javax.swing.JLabel noOfItemLbl;
    private javax.swing.JLabel noOfItemsLbl;
    private javax.swing.JSpinner noOfItemsRmvTF;
    private javax.swing.JSpinner noOfItemsTF;
    private javax.swing.JPanel pane;
    private javax.swing.JTextField priceTF;
    private javax.swing.JButton removeBtn1;
    private javax.swing.JButton showItemsBtn;
    // End of variables declaration//GEN-END:variables
}
